openapi: 3.0.2
info:
  title: OpenAI plugin for zen quotes
  description: Gets a random quote from zenquotes.io
  version: 1.0.0
  servers:
    - url: https://localhost:8080
paths:
  /quote:
    get:
      summary: Get a random quote
      description: Returns a random quote from zenquotes.io
      operationId: get_quote
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/get_quote_response"
components:
  schemas:
    get_quote_response:
      type: object
      properties:
        quote:
          type: string
          description: The quote